import AppKit
import QuartzCore

/// Continuous, bounded scene time: host pauses do not become camera jumps.
struct WorldClock {
    private(set) var elapsed=0.0
    private var previous:Double?
    mutating func reset(){elapsed=0;previous=nil}
    mutating func pause(){previous=nil}
    mutating func tick(_ time:Double,running:Bool){
        guard time.isFinite else{return}
        if running,let previous {elapsed+=max(0,min(0.25,time-previous))}
        previous=running ? time:nil
    }
}
func worldEase(_ x:Double)->Double {let a=min(1,max(0,x));return a*a*a*(a*(a*6-15)+10)}
struct WorldPoint:Equatable {var x:Double;var y:Double;var point:CGPoint {CGPoint(x:x,y:y)}}
struct WorldEdge:Equatable {let a:Int;let b:Int}
struct WorldCamera:Equatable {let x:Double;let y:Double;let zoom:Double}

/// A perfect maze, generated by a seeded depth-first walk; no external puzzle assets.
struct ResearchMaze:Equatable {
    let columns:Int,rows:Int
    let passages:[WorldEdge]
    let traversal:[Int]
    init(seed:UInt64,columns:Int=13,rows:Int=9){
        self.columns=max(2,columns);self.rows=max(2,rows)
        var r=ArtRandom(state:seed),seen=Set([0]),stack=[0],edges:[WorldEdge]=[],walk=[0]
        while let current=stack.last {
            let x=current%self.columns,y=current/self.columns
            let neighbors=[x>0 ? current-1:nil,x+1<self.columns ? current+1:nil,y>0 ? current-self.columns:nil,y+1<self.rows ? current+self.columns:nil].compactMap{$0}.filter{!seen.contains($0)}
            if neighbors.isEmpty {stack.removeLast();if let back=stack.last {walk.append(back)}}
            else {let next=neighbors[Int(r.next()*Double(neighbors.count))];edges.append(WorldEdge(a:current,b:next));seen.insert(next);stack.append(next);walk.append(next)}
        }
        passages=edges;traversal=walk
    }
    func open(_ a:Int,_ b:Int)->Bool {passages.contains{($0.a==a && $0.b==b)||($0.a==b && $0.b==a)}}
    func agent(_ time:Double)->WorldPoint {
        // Deliberate pauses followed by a smooth move. DFS includes real backtracking.
        let step=max(0,time)/8,index=Int(step)%traversal.count,next=(index+1)%traversal.count
        let a=traversal[index],b=traversal[next],f=worldEase((step-floor(step)-0.45)/0.55)
        return WorldPoint(x:Double(a%columns)*(1-f)+Double(b%columns)*f+0.5,y:Double(a/columns)*(1-f)+Double(b/columns)*f+0.5)
    }
}

/// Small drawing vocabulary for cached, original 2.5D scenery.
enum WorldInk {
    static func color(_ rgb:RGB,_ alpha:Double=1)->CGColor {rgb.color.withAlphaComponent(alpha).cgColor}
    static func blend(_ a:RGB,_ b:RGB,_ t:Double)->RGB {RGB(a.r+(b.r-a.r)*t,a.g+(b.g-a.g)*t,a.b+(b.b-a.b)*t)}
    static func polygon(_ c:CGContext,_ points:[CGPoint],_ color:RGB,_ alpha:Double=1){
        guard let first=points.first else{return};c.beginPath();c.move(to:first);for p in points.dropFirst(){c.addLine(to:p)};c.closePath();c.setFillColor(self.color(color,alpha));c.fillPath()
    }
    static func path(_ c:CGContext,_ points:[CGPoint],_ color:RGB,_ width:Double=1,_ alpha:Double=1){
        guard let first=points.first else{return};c.beginPath();c.move(to:first);for p in points.dropFirst(){c.addLine(to:p)};c.setStrokeColor(self.color(color,alpha));c.setLineWidth(width);c.setLineCap(.round);c.setLineJoin(.round);c.strokePath()
    }
    static func rect(_ c:CGContext,_ r:CGRect,_ color:RGB,_ alpha:Double=1){c.setFillColor(self.color(color,alpha));c.fill(r)}
    static func oval(_ c:CGContext,_ r:CGRect,_ color:RGB,_ alpha:Double=1){c.setFillColor(self.color(color,alpha));c.fillEllipse(in:r)}
    static func glow(_ c:CGContext,_ p:CGPoint,_ radius:Double,_ color:RGB,_ alpha:Double){
        guard let g=CGGradient(colorsSpace:CGColorSpace(name:CGColorSpace.sRGB),colors:[self.color(color,alpha),self.color(color,0)] as CFArray,locations:[0,1]) else{return}
        c.drawRadialGradient(g,startCenter:p,startRadius:0,endCenter:p,endRadius:radius,options:[])
    }
    static func softShadow(_ c:CGContext,_ center:CGPoint,_ width:Double,_ height:Double,_ color:RGB,_ alpha:Double){
        c.saveGState();c.translateBy(x:center.x,y:center.y);c.scaleBy(x:1,y:height/width);glow(c,.zero,width/2,color,alpha);c.restoreGState()
    }
    static func label(_ c:CGContext,_ value:String,_ p:CGPoint,_ size:Double,_ color:RGB,_ alpha:Double=1){
        withAppKit(c){(value as NSString).draw(at:p,withAttributes:[.font:NSFont.monospacedSystemFont(ofSize:size,weight:.regular),.foregroundColor:color.color.withAlphaComponent(alpha),.kern:1.1])}
    }
    static func image(_ size:CGSize,_ scale:Double=1,draw:(CGContext)->Void)->CGImage {
        let c=bitmap(width:max(1,Int(ceil(size.width*scale))),height:max(1,Int(ceil(size.height*scale))))!
        c.scaleBy(x:scale,y:scale);draw(c);return c.makeImage()!
    }
    static func layer(_ image:CGImage,_ rect:CGRect)->CALayer {let l=CALayer();l.contents=image;l.frame=rect;return l}
    static func dot(_ color:RGB,_ radius:Double)->CALayer {
        let l=CALayer();l.bounds=CGRect(x:0,y:0,width:radius*2,height:radius*2);l.cornerRadius=radius;l.backgroundColor=self.color(color)
        l.shadowColor=self.color(color);l.shadowOpacity=0.3;l.shadowRadius=radius*2;l.shadowOffset = .zero;return l
    }
}
